credentials:
  usernames:
    admin:
      email: cnbkrtl11@gmail.com
      name: Can Bakırtel
      password: '$2b$12$BqtHtrZfPr..zwVg5sob7eqgKYlPrrT0kTXugBmFT01dA8GrXWo4q' # generate_keys.py'den gelen ilk hash
    rhendricks:
      email: rhendricks@gmail.com
      name: Richard Hendricks
      password: '$2b$12$gIqHjCLxMPnzzsgt9Tk80u9feBQHpUAt50hBSO5BByjCpgKRJgn5W' # generate_keys.py'den gelen ikinci hash
cookie:
  expiry_days: 30
  name: 'vervegrand_portal'
  key: '57b9996a7ac860f4aa8b36873f5b5a192aaba3eac4bbc39ba3db8bc0c7bc3d87' # Bu anahtarı rastgele bir şeyle değiştirin
